/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://zo7yp5lozrewhodi6cqmy4i2ku.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2e3npgt7w5eixgu3db64jfpnku",
    "aws_cognito_identity_pool_id": "us-east-1:ee27a282-a41b-4151-9fb2-16753b4997f1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_bdmtsP9RA",
    "aws_user_pools_web_client_id": "4cfipg44kagkur1vmasmmmmrqk",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
